### ISSUE TITLE
controls

### ISSUE THREAD

**Issue by spaniakos** [likeconan/flutter_video_player#4]
Hello there, amazing work.

i have two requests if you feeling like it
1) can the hideControls flag be populated to the players across techs?
2) can you extend the library to handle setVolume via a hook ?

Also i think that thumbnail isn't being populated to the web player.
Thank you! 

I can help if that helps

**Comment by likeconan** [comment]
Hi @spaniakos  thanks for your issue.

Let's clear things out:
1. I think hideControls work in android and iOS but not web, do you want to implement in that?
2. Do you want to setVolume in flutter side?

Thumbnails in mobile does not work for web, what do you exactly need in web player since videojs has covered most of functions I think

**Comment by spaniakos** [comment]
I am trying to find a lib that would resolve the issue flutter has with mobile web and auto play ( for some reason on mobile browsers flutter has issue with continuous auto play of videos for example with a page view, and the promise gets reset every 5 seconds from last user action )  

Also I would love a set volume feature in the lib since this is a fallback for auto play muted, and when the controls are off ( which cannot be on video js web currently ) I set volume call helps as you can hook that on gesture or external button 

I can try to extend your code for that ( fresh to flutter , old in programming ) 

About the thumbnail it was just an observation

**Comment by likeconan** [comment]
Ok, I see your point, I think you may have a try with https://cloudinary.com/documentation/cloudinary_video_player. It's autoplay in mobile and set it as mute

**Comment by spaniakos** [comment]
I will try to extend you library since it uses video js for handling web 

If I get results I'll keep you posted 

I want to make a tri-code single library solution
