### ISSUE TITLE
flutter web crash in production Uncaught MissingPluginException

### ISSUE THREAD

**Issue by fernandasdias** [likeconan/flutter_video_player#5]
My video is gray and not working in production, but it works on my localhost. 
This is the error that I caught on my console output:
Uncaught MissingPluginException(No implementation found for method ready on channel oneplusdream/video_channel_0)

I have added those linex on my index.html:
<link href="https://vjs.zencdn.net/8.0.4/video-js.css" rel="stylesheet" />
  <script src="https://vjs.zencdn.net/8.0.4/video.min.js"></script>

**Comment by likeconan** [comment]
@fernandasdias  Could you share your production demo site, I need to check it out.

**Comment by likeconan** [comment]
Close since no response
